import { RestaurantConfig } from './types';

const defaultSchedule = { isOpen: true, start: "09:00", end: "23:00" };

export const DEFAULT_CONFIG: RestaurantConfig = {
  name: "FASTMENU",
  description: "خدمة المنيو الالكتروني للمطاعم. اطلب، ادفع، واستمتع بسرعة البرق.",
  logo: "https://via.placeholder.com/200", 
  coverImage: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=1000&auto=format&fit=crop",
  currency: "ر.س",
  primaryColor: "#fbbf24", 
  languages: ['ar'],
  isOrderingEnabled: true,
  socials: {
    whatsapp: "",
    instagram: "",
    facebook: "",
    tiktok: "",
    googleMaps: "",
  },
  workingHours: {
    saturday: { ...defaultSchedule },
    sunday: { ...defaultSchedule },
    monday: { ...defaultSchedule },
    tuesday: { ...defaultSchedule },
    wednesday: { ...defaultSchedule },
    thursday: { ...defaultSchedule },
    friday: { isOpen: true, start: "13:00", end: "23:00" },
  },
  offers: [],
  categories: [],
  dishes: []
};

export const TRANSLATIONS = {
  ar: {
    // Menu
    openNow: "مفتوح الآن",
    closedNow: "مغلق الآن",
    rateExp: "قيم تجربتك",
    offers: "العروض الخاصة",
    save: "وفر",
    unavailable: "غير متاح",
    viewOrder: "شاهد الطلب",
    cart: "سلة الطلبات",
    emptyCart: "السلة فارغة",
    total: "المجموع الكلي",
    namePlaceholder: "الاسم الكريم",
    tablePlaceholder: "رقم الطاولة",
    phonePlaceholder: "رقم الهاتف",
    addressPlaceholder: "العنوان الكامل (المنطقة، الشارع، رقم المنزل)",
    codePlaceholder: "كود التحقق (مكتوب أسفل رمز QR)",
    back: "عودة",
    confirmOrder: "تأكيد الطلب",
    sending: "جاري الإرسال...",
    completeOrder: "إتمام الطلب",
    orderSuccess: "تم استلام طلبك بنجاح!",
    orderSuccessMsg: "سيتم تحضير طلبك وإحضاره لطاولتك قريباً.",
    addToOrder: "إضافة إلى الطلب",
    orderingDisabled: "الطلب متوقف حالياً",
    soldOut: "نفذت الكمية",
    language: "اللغة",
    workingHours: "أوقات العمل",
    dineIn: "داخل المطعم",
    delivery: "توصيل",
    deliveryDetails: "بيانات التوصيل",
    saturday: "السبت",
    sunday: "الأحد",
    monday: "الإثنين",
    tuesday: "الثلاثاء",
    wednesday: "الأربعاء",
    thursday: "الخميس",
    friday: "الجمعة",
    dashboard: "لوحة التحكم",
    manageMenu: "إدارة القائمة والطلبات",
    backToSelect: "العودة لصفحة الاختيار",
    orders: "الطلبات",
    analytics: "الإحصائيات",
    menu: "قائمة الطعام",
    settings: "الإعدادات",
    logout: "خروج",
    welcomeTitle: "مرحباً بك في FASTMENU!",
    welcomeMsg: "يرجى إكمال ملف المطعم (الاسم، الشعار، والوصف) لتبدأ باستقبال الطلبات بشكل صحيح.",
    receivedOrders: "الطلبات المستلمة",
    update: "تحديث",
    noOrders: "لا توجد طلبات حالياً",
    table: "طاولة",
    new: "جديد",
    preparing: "تحضير",
    completed: "مكتمل",
    startPrep: "بدء التحضير",
    complete: "إكمال الطلب",
    cancel: "إلغاء",
    restaurantSettings: "إعدادات المطعم",
    orderingPhone: "استقبال الطلبات عبر الهاتف",
    orderingPhoneDesc: "تفعيل أو إيقاف إمكانية إرسال الطلبات من صفحة المنيو",
    active: "مفعل",
    inactive: "متوقف",
    closed: "مغلق",
    restaurantName: "اسم المطعم",
    restaurantLogo: "شعار المطعم (Logo)",
    restaurantDesc: "وصف المطعم",
    coverImage: "صورة الغلاف",
    currency: "العملة",
    socialLinks: "روابط التواصل الاجتماعي",
    saveChanges: "حفظ التعديلات",
    saving: "جاري الحفظ...",
    menuManagement: "إدارة القائمة",
    newCategory: "قسم جديد",
    homeOffers: "عروض الشاشة الرئيسية",
    addOffer: "إضافة عرض",
    noOffers: "لا توجد عروض حالياً.",
    edit: "تعديل",
    hidden: "مخفي",
    showSection: "إظهار القسم",
    hideSection: "إخفاء القسم",
    available: "متاح",
    addDish: "إضافة طبق",
    hiddenSectionMsg: "هذا القسم مخفي ولا يظهر الأطباق بداخله للزبائن.",
    qrCodes: "رموز الطاولات (QR)",
    qrDesc: "قم بطباعة رموز QR ولصقها على الطاولات.",
    generateQr: "توليد الرموز",
    printQr: "طباعة",
    tableCount: "عدد الطاولات",
    scanToOrder: "امسح للطلب",
    verificationCode: "كود التحقق",
    totalRevenue: "إجمالي المبيعات",
    totalOrders: "عدد الطلبات",
    averageOrder: "متوسط الطلب",
    bestSellers: "الأطباق الأكثر مبيعاً",
    timeRange: "النطاق الزمني",
    today: "اليوم",
    week: "أسبوع",
    month: "شهر",
    custom: "مخصص",
    addEditOffer: "إضافة/تعديل عرض",
    offerTitle: "عنوان العرض",
    newPrice: "السعر الجديد",
    oldPrice: "السعر القديم",
    offerImage: "صورة العرض",
    offerActive: "العرض مفعل ويظهر في القائمة",
    saveOffer: "حفظ العرض",
    addEditCategory: "تعديل/إضافة قسم",
    catName: "اسم القسم",
    catImage: "صورة القسم",
    catActive: "القسم متاح (يظهر للزبائن)",
    dishDetails: "تفاصيل الطبق",
    dishName: "اسم الطبق",
    selectCat: "اختر القسم",
    price: "السعر",
    prepTime: "مدة التحضير (دقائق)",
    calories: "السعرات (اختياري)",
    dishImage: "صورة الطبق",
    changeImage: "تغيير الصورة",
    clickUpload: "اضغط لرفع صورة",
    aiWrite: "كتابة ذكية (Gemini)",
    generating: "جاري التوليد...",
    dishActive: "الطبق متاح للطلب",
    cancelBtn: "إلغاء",
    saveDish: "حفظ الطبق",
    chooseCategoryStyle: "شكل عرض الأقسام",
    styleCircular: "دوائر كلاسيكية",
    stylePills: "أزرار عريضة"
  }
};
