import { RestaurantConfig } from './types';

const defaultSchedule = { isOpen: true, start: "09:00", end: "23:00" };

export const DEFAULT_CONFIG: RestaurantConfig = {
  name: "FASTMENU",
  description: "Service de menu numérique pour restaurants. Commandez, payez et profitez à la vitesse de l'éclair.",
  logo: "https://via.placeholder.com/200", 
  coverImage: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=1000&auto=format&fit=crop",
  currency: "DA",
  primaryColor: "#fbbf24", 
  languages: ['ar', 'fr'], // تفعيل اللغتين معاً
  isOrderingEnabled: true,
  socials: {
    whatsapp: "",
    instagram: "",
    facebook: "",
    tiktok: "",
    googleMaps: "",
  },
  workingHours: {
    saturday: { ...defaultSchedule },
    sunday: { ...defaultSchedule },
    monday: { ...defaultSchedule },
    tuesday: { ...defaultSchedule },
    wednesday: { ...defaultSchedule },
    thursday: { ...defaultSchedule },
    friday: { isOpen: true, start: "13:00", end: "23:00" },
  },
  offers: [],
  categories: [],
  dishes: []
};

export const TRANSLATIONS = {
  ar: {
    openNow: "مفتوح الآن",
    closedNow: "مغلق الآن",
    rateExp: "قيم تجربتك",
    offers: "العروض الخاصة",
    save: "وفر",
    unavailable: "غير متاح",
    viewOrder: "شاهد الطلب",
    cart: "سلة الطلبات",
    emptyCart: "السلة فارغة",
    total: "المجموع الكلي",
    namePlaceholder: "الاسم الكريم",
    tablePlaceholder: "رقم الطاولة",
    phonePlaceholder: "رقم الهاتف",
    addressPlaceholder: "العنوان الكامل (المنطقة، الشارع، رقم المنزل)",
    codePlaceholder: "كود التحقق (مكتوب أسفل رمز QR)",
    back: "عودة",
    confirmOrder: "تأكيد الطلب",
    sending: "جاري الإرسال...",
    completeOrder: "إتمام الطلب",
    orderSuccess: "تم استلام طلبك بنجاح!",
    orderSuccessMsg: "سيتم تحضير طلبك وإحضاره لطاولتك قريباً.",
    addToOrder: "إضافة إلى الطلب",
    orderingDisabled: "الطلب متوقف حالياً",
    soldOut: "نفذت الكمية",
    language: "اللغة",
    workingHours: "أوقات العمل",
    dineIn: "داخل المطعم",
    delivery: "توصيل",
    deliveryDetails: "بيانات التوصيل",
    saturday: "السبت",
    sunday: "الأحد",
    monday: "الإثنين",
    tuesday: "الثلاثاء",
    wednesday: "الأربعاء",
    thursday: "الخميس",
    friday: "الجمعة",
    dashboard: "لوحة التحكم",
    manageMenu: "إدارة القائمة والطلبات",
    backToSelect: "العودة لصفحة الاختيار",
    orders: "الطلبات",
    analytics: "الإحصائيات",
    menu: "قائمة الطعام",
    settings: "الإعدادات",
    logout: "خروج",
    welcomeTitle: "مرحباً بك في FASTMENU!",
    welcomeMsg: "يرجى إكمال ملف المطعم (الاسم، الشعار، والوصف) لتبدأ باستقبال الطلبات بشكل صحيح.",
    receivedOrders: "الطلبات المستلمة",
    update: "تحديث",
    noOrders: "لا توجد طلبات حالياً",
    table: "طاولة",
    new: "جديد",
    preparing: "تحضير",
    completed: "مكتمل",
    startPrep: "بدء التحضير",
    complete: "إكمال الطلب",
    cancel: "إلغاء",
    restaurantSettings: "إعدادات المطعم",
    orderingPhone: "استقبال الطلبات عبر الهاتف",
    orderingPhoneDesc: "تفعيل أو إيقاف إمكانية إرسال الطلبات من صفحة المنيو",
    active: "مفعل",
    inactive: "متوقف",
    closed: "مغلق",
    restaurantName: "اسم المطعم",
    restaurantLogo: "شعار المطعم (Logo)",
    restaurantDesc: "وصف المطعم",
    coverImage: "صورة الغلاف",
    currency: "العملة",
    socialLinks: "روابط التواصل الاجتماعي",
    saveChanges: "حفظ التعديلات",
    saving: "جاري الحفظ...",
    menuManagement: "إدارة القائمة",
    newCategory: "قسم جديد",
    homeOffers: "عروض الشاشة الرئيسية",
    addOffer: "إضافة عرض",
    noOffers: "لا توجد عروض حالياً.",
    edit: "تعديل",
    hidden: "مخفي",
    showSection: "إظهار القسم",
    hideSection: "إخفاء القسم",
    available: "متاح",
    addDish: "إضافة طبق",
    hiddenSectionMsg: "هذا القسم مخفي ولا يظهر الأطباق بداخله للزبائن.",
    qrCodes: "رموز الطاولات (QR)",
    qrDesc: "قم بطباعة رموز QR ولصقها على الطاولات.",
    generateQr: "توليد الرموز",
    printQr: "طباعة",
    tableCount: "عدد الطاولات",
    scanToOrder: "امسح للطلب",
    verificationCode: "كود التحقق",
    totalRevenue: "إجمالي المبيعات",
    totalOrders: "عدد الطلبات",
    averageOrder: "متوسط الطلب",
    bestSellers: "الأطباق الأكثر مبيعاً",
    timeRange: "النطاق الزمني",
    today: "اليوم",
    week: "أسبوع",
    month: "شهر",
    custom: "مخصص",
    addEditOffer: "إضافة/تعديل عرض",
    offerTitle: "عنوان العرض",
    newPrice: "السعر الجديد",
    oldPrice: "السعر القديم",
    offerImage: "صورة العرض",
    offerActive: "العرض مفعل ويظهر في القائمة",
    saveOffer: "حفظ العرض",
    addEditCategory: "تعديل/إضافة قسم",
    catName: "اسم القسم",
    catImage: "صورة القسم",
    catActive: "القسم متاح (يظهر للزبائن)",
    dishDetails: "تفاصيل الطبق",
    dishName: "اسم الطبق",
    selectCat: "اختر القسم",
    price: "السعر",
    prepTime: "مدة التحضير (دقائق)",
    calories: "السعرات (اختياري)",
    dishImage: "صورة الطبق",
    changeImage: "تغيير الصورة",
    clickUpload: "اضغط لرفع صورة",
    aiWrite: "كتابة ذكية (Gemini)",
    generating: "جاري التوليد...",
    dishActive: "الطبق متاح للطلب",
    cancelBtn: "إلغاء",
    saveDish: "حفظ الطبق",
    chooseCategoryStyle: "شكل عرض الأقسام",
    styleCircular: "دوائر كلاسيكية",
    stylePills: "أزرار عريضة"
  },
  fr: {
    openNow: "Ouvert maintenant",
    closedNow: "Fermé maintenant",
    rateExp: "Évaluez votre expérience",
    offers: "Offres Spéciales",
    save: "Économisez",
    unavailable: "Indisponible",
    viewOrder: "Voir la commande",
    cart: "Votre Panier",
    emptyCart: "Le panier est vide",
    total: "Total général",
    namePlaceholder: "Votre nom",
    tablePlaceholder: "N° de Table",
    phonePlaceholder: "N° de Téléphone",
    addressPlaceholder: "Adresse complète",
    codePlaceholder: "Code de vérification",
    back: "Retour",
    confirmOrder: "Confirmer la commande",
    sending: "Envoi en cours...",
    completeOrder: "Finaliser la commande",
    orderSuccess: "Commande réussie !",
    orderSuccessMsg: "Votre commande sera servie bientôt.",
    addToOrder: "Ajouter au panier",
    orderingDisabled: "Commandes désactivées",
    soldOut: "Épuisé",
    language: "Langue",
    workingHours: "Horaires",
    dineIn: "Sur place",
    delivery: "Livraison",
    deliveryDetails: "Détails de livraison",
    saturday: "Samedi",
    sunday: "Dimanche",
    monday: "Lundi",
    tuesday: "Mardi",
    wednesday: "Mercredi",
    thursday: "Jeudi",
    friday: "Vendredi",
    dashboard: "Tableau de bord",
    manageMenu: "Gestion Menu",
    backToSelect: "Retour",
    orders: "Commandes",
    analytics: "Statistiques",
    menu: "Menu",
    settings: "Paramètres",
    logout: "Déconnexion",
    welcomeTitle: "Bienvenue !",
    welcomeMsg: "Veuillez compléter votre profil.",
    receivedOrders: "Commandes reçues",
    update: "Mettre à jour",
    noOrders: "Aucune commande",
    table: "Table",
    new: "Nouveau",
    preparing: "En préparation",
    completed: "Terminé",
    startPrep: "Préparer",
    complete: "Terminer",
    cancel: "Annuler",
    restaurantSettings: "Paramètres Restaurant",
    orderingPhone: "Prise de commande",
    orderingPhoneDesc: "Activer les commandes via le menu",
    active: "Activé",
    inactive: "Désactivé",
    closed: "Fermé",
    restaurantName: "Nom du Restaurant",
    restaurantLogo: "Logo",
    restaurantDesc: "Description",
    coverImage: "Image de couverture",
    currency: "Devise",
    socialLinks: "Réseaux Sociaux",
    saveChanges: "Enregistrer",
    saving: "Enregistrement...",
    menuManagement: "Gestion Menu",
    newCategory: "Nouvelle Catégorie",
    homeOffers: "Offres d'accueil",
    addOffer: "Ajouter une offre",
    noOffers: "Aucune offre.",
    edit: "Modifier",
    hidden: "Masqué",
    showSection: "Afficher",
    hideSection: "Masquer",
    available: "Disponible",
    addDish: "Ajouter un plat",
    hiddenSectionMsg: "Cette section est masquée.",
    qrCodes: "Codes QR",
    qrDesc: "Gérer vos QR codes table.",
    generateQr: "Gérer les codes",
    printQr: "Imprimer",
    tableCount: "Nombre de tables",
    scanToOrder: "Scannez pour commander",
    verificationCode: "Code de vérification",
    totalRevenue: "Chiffre d'affaires",
    totalOrders: "Total commandes",
    averageOrder: "Panier moyen",
    bestSellers: "Meilleures ventes",
    timeRange: "Période",
    today: "Aujourd'hui",
    week: "Semaine",
    month: "Mois",
    custom: "Personnalisé",
    addEditOffer: "Modifier l'offre",
    offerTitle: "Titre",
    newPrice: "Nouveau prix",
    oldPrice: "Ancien prix",
    offerImage: "Image",
    offerActive: "Offre active",
    saveOffer: "Enregistrer",
    addEditCategory: "Gérer la catégorie",
    catName: "Nom",
    catImage: "Image",
    catActive: "Disponible",
    dishDetails: "Détails du plat",
    dishName: "Nom",
    selectCat: "Catégorie",
    price: "Prix",
    prepTime: "Temps de prép.",
    calories: "Calories",
    dishImage: "Image",
    changeImage: "Modifier l'image",
    clickUpload: "Uploader",
    aiWrite: "Rédaction IA",
    generating: "Génération...",
    dishActive: "Disponible",
    cancelBtn: "Annuler",
    saveDish: "Enregistrer",
    chooseCategoryStyle: "Style d'affichage",
    styleCircular: "Cercles",
    stylePills: "Boutons"
  }
};
